# Generated by Django 4.0.5 on 2022-10-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='uploads',
            field=models.FloatField(default=5),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo', to='isabuhaywebapp.promooptions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='isabuhaywebapp.promooptions')),
            ],
        ),
    ]
