# Generated by Django 4.1.2 on 2022-10-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0003_alter_payments_promo_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbctestresult',
            name='dateReceived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cbctestresult',
            name='dateRequested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
