# Generated by Django 4.1.2 on 2022-10-27 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0006_alter_cbctestresultimage_testimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbctestresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
