# Generated by Django 4.1.3 on 2022-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0009_user_date_created_alter_user_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
    ]
