# Generated by Django 4.1.3 on 2022-12-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0011_rename_absoluteseg_cbctestresult_absoluteneutrophilscount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CBCTestResultDocx',
            new_name='CBCTestResultDocument',
        ),
    ]
