# Generated by Django 4.1.3 on 2022-12-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0012_rename_cbctestresultdocx_cbctestresultdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromoOptions',
            new_name='Promo',
        ),
    ]
