# Generated by Django 4.1.3 on 2022-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isabuhaywebapp', '0014_rename_payments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbctestresultdocument',
            name='testDocx',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cbctestresultimage',
            name='testImage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cbctestresultpdf',
            name='testPDF',
            field=models.FileField(upload_to=''),
        ),
    ]
